name: Publish Web

on:
  push:
    branches: master

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-v0.3.4
      - run: |
          if [ ! -f $HOME/.cargo/bin/rustsec-admin ]; then
           cargo install rustsec-admin --git https://github.com/ammaraskar/rustsec-admin.git --branch full_changes
          fi
          rustsec-admin web .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update gh-pages" || true
          git push || true
